### ISSUE TITLE
[Traefik Plugin Catalog] Plugin Analyzer has detected a problem.

### ISSUE THREAD

**Issue by traefiker** [project-echo/traefik-ocsp#2]
The plugin was not imported into Traefik Plugin Catalog.

Cause:
```
failed to run the plugin with Yaegi: failed to eval `CreateConfig` function: 1:28: undefined: traefik_ocsp
```
Traefik Plugin Analyzer will restart when you will close this issue.

If you believe there is a problem with the Analyzer or this issue is the result of a false positive, please fill an issue on [piceus](https://github.com/traefik/piceus) repository.

**Comment by erkiesken** [comment]
Yaegi seems to [convert](https://github.com/traefik/piceus/blob/909a0aa078ceb53ca4af6dd4b299c4efc0b0335e/pkg/core/yaegi.go#L156) dashes in repo name to underscores to match the base package name. So fix is to use `package traefik_ocsp` instead of `package ocsp`, since repo name is `traefik-ocsp`.
